### ISSUE TITLE
Self-Signed Certificate support

### ISSUE THREAD

**Issue by dncrews** [simple-app/simple-http-proxy#7]
We're currently working on building an internal application, and we have a self-signed certificate that we need to allow. Doing this locally, simple-http-proxy would be a nice help, but I don't have a way to pass  `rejectUnauthorized=false`.

Please assist.

**Comment by camshaft** [comment]
You can use the [onrequest](https://github.com/simple-app/simple-http-proxy#onrequest) option to override any of the parameters you need, including `rejectUnauthorized`.
