### ISSUE TITLE
Forwarding data on POST?

### ISSUE THREAD

**Issue by omichelsen** [simple-app/simple-http-proxy#8]
Hi, I'm failing to get your proxy to work with POST containing (json) data in the body.

Looking through the code I can find nowhere `req.write(data)` is called, so is this just not possible, or do I have do something else to forward the data?

**Comment by camshaft** [comment]
POSTs should be working just fine. You can see the pipe call [here](https://github.com/simple-app/simple-http-proxy/blob/master/index.js#L140)

**Comment by omichelsen** [comment]
Yeah, I just got a lot of empty POST and GET's piped just fine, and as soon as I put JSON body in a call, it breaks. But it's probably on my end, so I'll close this issue. Thanks for your response.

**Comment by camshaft** [comment]
if you're using the proxy with connect or express you need to make sure the bodyParser middleware is disabled since it will buffer the body into `req.body`. let me know if you have any other issues

**Comment by omichelsen** [comment]
Ah, that might indeed be what conflicts for me. I'll try and see if I can disable it - thanks for the input.
