### ISSUE TITLE
Proxy through a web proxy?

### ISSUE THREAD

**Issue by Kikketer** [simple-app/simple-http-proxy#9]
I might be crazy, but I need to proxy requests through a corporate proxy.
The process is something like "app A requests resource B" > "app A routes through corporate proxy to get resource B".  App "A" is using the simple-http-proxy to avoid CORS issues.

Is this at all possible?

Not sure what you are using behind the scenes, but I did see some proxy type mechanism with request (which doesn't really do what I need):
https://github.com/request/request#proxies

**Comment by camshaft** [comment]
I'm not sure I totally understand your setup but I'm not sure this is what you want. simple-http-proxy is a reverse proxy (http://en.wikipedia.org/wiki/Proxy_server#Types_of_proxy) vs a forward proxy, which is what I think you want. Reverse proxies generally mean a public server requesting resources to one or few backend servers. Forward proxies, on the other hand, usually connect to the whole web.

It basically boils down to "am I trying to hit a particular server or just the general web?" If it's the first then simple-http-proxy is the answer. Keep in mind this would have to sit outside of the firewall and still be accessible from within.

Hopefully that's helpful

**Comment by Kikketer** [comment]
Ok I think I understand, thanks for the link.
What I'm actually trying to do is avoid having source systems add CORS functionality.  My app is a set of "cards" that access different resources, and a bright idea flew into my head to allow users to build their own cards (say a weather or "crazy system A").  But of course our application is behind a corporate firewall which requires the use of HTTP_PROXY settings for things like GIT or NPM.

Right now I'm able to access internal resources that don't require authentication.  My next step was to see if I can get external resources through this corporate proxy.
